### PR TITLE
Comparing model runs with different ECS values

### LINKED ISSUE #18: ECS Sensitivity Testing
Do 20-30 runs with different (uniformly spaced) ECS values within the IPCC range to test how sensitive Hector is to changes in ECS.

### PR DESCRIPTION
**Pull request by ptrscll**
I tried changing ECS values within the IPCC range of 2-5. At the moment, I have a spaghetti plot with all the temperature and CO2 results, but I also plan on making a plot showing the difference between the new runs and the run with the baseline ECS of 3.

### CODE REVIEW

**Comment by kdorheim** [comment]
image

@ptrscll, what sort of conclusions can you draw from this plot? Would it be helpful to include S as one of the calibration parameters?

**Comment by ptrscll** [comment]
I think this plot indicates that changing ECS can have a pretty substantial effect on temperature predictions, which makes me think that it would be helpful to try including it as a calibration parameter.

**Comment by kdorheim** [comment]
Let's give it a try!

**Comment by kdorheim** [comment]
@ptrscll, could you do a similar analysis of changing ocean heat diffusivity over a somewhat large range? While keeping S fixed at 3?

**Pull request merged**
