### PR TITLE
Plotted CH4 and N2O concentrations over time

### LINKED ISSUE #22: Checking N2O and CH4 Data
Check to make sure Hector's N2O and CH4 concentrations look reasonable and match historical record

### PR DESCRIPTION
**Pull request by ptrscll**
Wrote script to plot historical and Hector CH4 and N2O concentrations over time. Let me know what you think of the plot @kdorheim 

ch4_n2o_plot

### CODE REVIEW

**Comment by kdorheim** [comment]
@ptrscll could you add the CH4 and N2O concentrations for the historical period from one of the input tables?

**Comment by ptrscll** [comment]
Just added in the data - it looks like it lines up exactly with the Meinhausen data (aside from 1750-1850 where the data's missing)

ch4_n2o_plot

**Comment by kdorheim** [comment]
👍 okay great! 

Alright, could you do the following historical runs 
1. emission driven (baseline)
2. with [n2o] constraints only 
3. with [ch4] constraints only 
4. with [ch4] and [n2o] constraints only 

I would like to see how far how much of an effect this has on global mean surface temperature

**Comment by ptrscll** [comment]
Just did those runs - there didn't seem to particularly large effect on GMST (at least relative to the changes with ECS):
ch4_n2o_constr_comparison

**Comment by kdorheim** [comment]
Hmmm well that is good for past Hector things but a tad disappointing for us! Thanks for checking!

**Pull request merged**
